### ISSUE TITLE
贪心算法的部分题目的空间复杂度讨论

### ISSUE THREAD

**Issue by GitHubQAQ** [youngyangyang04/leetcode-master#1334]
如题目56，435，452等题目出现了sort算法，是否应该考虑快排算法带来的空间复杂度？
![image](https://user-images.githubusercontent.com/31883473/168470448-015faeea-cd78-4d7d-b6e7-d644a88b4b21.png)

**Comment by youngyangyang04** [comment]
最差情况(倒序)时，需要n次递归调用。因此确实需要O(n)的栈空间

**Comment by GitHubQAQ** [comment]
> 最差情况(倒序)时，需要n次递归调用。因此确实需要O(n)的栈空间

后面有时间会再深入了解一下。作为题解，这部分的复杂度是否需要考虑进去，还不明确。
