### ISSUE TITLE
如何更进一步提升算法能力

### ISSUE THREAD

**Issue by xiaofei-2020** [youngyangyang04/leetcode-master#1365]
刷完随想录后，如果想更进一步学习提升算法能力，Carl哥有什么建议吗？非常感谢！

**Comment by youngyangyang04** [comment]
看到你给仓库每天题目提交了 typescript 版本，非常感谢🌹 

一般来说，代码随想录刷一遍还是不够了，至少刷两遍，才能理解各个题目背后的联系。 之后可以刷一下 力扣hot100，来补充一下热点题目，基本就差不多了。
