### ISSUE TITLE
vim.md 错别字

### ISSUE THREAD

**Issue by Debbl** [youngyangyang04/leetcode-master#1716]
https://github.com/youngyangyang04/leetcode-master/blob/563cd8255131f735472949b54bf07d2aa13894d5/problems/%E5%89%8D%E5%BA%8F/vim.md?plain=1#L66

这里的“安防”是错别字吗？

**Comment by Logenleedev** [comment]
是的。我提交了一个PR

**Comment by Logenleedev** [comment]
可以close了
