### ISSUE TITLE
【图片挂了】

### ISSUE THREAD

**Issue by LookSin** [youngyangyang04/leetcode-master#1846]
卡哥，网站的图片挂了，不止一处加载不出来。
![image](https://user-images.githubusercontent.com/109679879/210755864-d38c0e2f-2673-4899-95f8-a6cb27d5d03b.png)

**Comment by youngyangyang04** [comment]
链接已经更新，感谢反馈🌹

**Comment by Logenleedev** [comment]
楼主可以close了
