### ISSUE TITLE
图片错位 + 动画 bug

### ISSUE THREAD

**Issue by Logenleedev** [youngyangyang04/leetcode-master#1854]
找到两个 bug。我 clone 到本地用 vscode 的 markdown previewer 看了一下倒是没什么问题

**问题1: 图片错位**

地址：0028.实现strStr.md ｜ _为什么一定要用前缀表_ 章节

<img width="991" alt="image" src="https://user-images.githubusercontent.com/47022821/211175333-be9f4dd7-86b8-45a0-9574-8b6d0cb66081.png">

**问题2: 动画 bug**

地址：0028.实现strStr.md ｜ _如何计算前缀表_ 章节 最后一个动画

貌似动画刚开始立刻就卡停了不知道什么原因

**Comment by youngyangyang04** [comment]
收到，动画问题，我更新了链接，你看github上动画显示应该没问题

**Comment by Logenleedev** [comment]
hello 卡哥！感谢回复。貌似还是有点问题。如下图：
<img width="640" alt="image" src="https://user-images.githubusercontent.com/47022821/211379735-20245651-df25-492a-bb38-0e478533d8ae.png">

**Comment by youngyangyang04** [comment]
现在应该是正常了，可能当时 刚替换gif资源导致的
