### ISSUE TITLE
图片错误

### ISSUE THREAD

**Issue by Logenleedev** [youngyangyang04/leetcode-master#1861]
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/47022821/212488743-b911b3d7-f622-4589-9978-e7a735e35d25.png">
 55 跳跃游戏：

右图中下标 ```i = 0```这个范围是不是错了。最大时能覆盖到```i = 2```但是图中只覆盖到了```i = 1```

**Comment by youngyangyang04** [comment]
是的，感谢指正🌹
