### ISSUE TITLE
哈希表-两个数组的交集-其他语言版本typo

### ISSUE THREAD

**Issue by JayLi1209** [youngyangyang04/leetcode-master#1862]
第21行comment应该是“集合”，打错成“几何”了。
[这里](https://programmercarl.com/0349.%E4%B8%A4%E4%B8%AA%E6%95%B0%E7%BB%84%E7%9A%84%E4%BA%A4%E9%9B%86.html#%E5%85%B6%E4%BB%96%E8%AF%AD%E8%A8%80%E7%89%88%E6%9C%AC)

**Comment by Undertone0809** [comment]
#1863

**Comment by Logenleedev** [comment]
可以 close 了
