### ISSUE TITLE
请问网站是用什么开源框架搭建的呢

### ISSUE THREAD

**Issue by smartboy37597** [youngyangyang04/leetcode-master#1957]
请问网站是用什么开源框架搭建的呢，网上已经看到好几款相同UI风格的，想学习一下

**Comment by Lzzzs** [comment]
https://vuepress.vuejs.org/zh/

**Comment by smartboy37597** [comment]
> https://vuepress.vuejs.org/zh/
谢谢回答 👍

**Comment by smartboy37597** [comment]
> https://vuepress.vuejs.org/zh/

老哥知道用的什么主题吗

**Comment by Lzzzs** [comment]
这我就不清楚了，你可以都试试看
