### ISSUE TITLE
各个类型的经典题目刷题顺序看不到

### ISSUE THREAD

**Issue by hwb0314** [youngyangyang04/leetcode-master#2]
大神，你好。readme里面的“各个类型的经典题目刷题顺序”内容看不到。请问是什么回事呢？

**Comment by Alice-Wang-0824** [comment]
你找错人了吧？我不清楚你在说啥啊，不好意思。我没经常用github或者leetcode啊，你怎么发到我邮箱来的，我一头雾水------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Weibo&amp;nbsp;Huang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月27日(星期五) 晚上10:20
收件人:&nbsp;&quot;youngyangyang04/leetcode-master&quot;<leetcode-master@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[youngyangyang04/leetcode-master] 各个类型的经典题目刷题顺序看不到 (#2)

**Comment by Alice-Wang-0824** [comment]
好吧，我现在看到了，但是这个我也不知道怎么回事啊，你问问其他人咯

**Comment by youngyangyang04** [comment]
> 好吧，我现在看到了，但是这个我也不知道怎么回事啊，你问问其他人咯

我已经更新了，因为发现一些公众号抄袭我的Github，所以我一气之下把他隐藏了，现在已经更新了LeetCode 刷题攻略，和算法文章精选保持一个顺序哈，算法文章精选比之前的LeetCode 刷题攻略更全！

**Comment by youngyangyang04** [comment]
> 大神，你好。readme里面的“各个类型的经典题目刷题顺序”内容看不到。请问是什么回事呢？

我已经更新了，因为发现一些公众号抄袭我的Github，所以我一气之下把他隐藏了，现在已经更新了LeetCode 刷题攻略，和算法文章精选保持一个顺序哈，算法文章精选比之前的LeetCode 刷题攻略更全！
