### ISSUE TITLE
LeetCode 最强题解: 0034题链接跳转不对

### ISSUE THREAD

**Issue by gds12345** [youngyangyang04/leetcode-master#3]
如图，这个链接跳转错了。。
![image](https://user-images.githubusercontent.com/30205371/103168154-b298f000-486b-11eb-8893-9b03eb9192bb.png)

**Comment by youngyangyang04** [comment]
> 如图，这个链接跳转错了。。
> ![image](https://user-images.githubusercontent.com/30205371/103168154-b298f000-486b-11eb-8893-9b03eb9192bb.png)

感谢指针哈，已修复！
