### ISSUE TITLE
0583.两个字符串的删除操作

### ISSUE THREAD

**Issue by TDDpro** [youngyangyang04/leetcode-master#336]
word1[i]!=word2[j]时只要考虑两种情况
- dp[i-1][j]+1
- dp[i][j-1]+1

dp[i-1][j-1]+2包含在上述情况中了
```c++
if(word1[i]==word2[j]){
        dp[i][j]=dp[i-1][j-1];
 }
  else{
         dp[i][j]=min(dp[i-1][j],dp[i][j-1])+1;
 }

**Comment by youngyangyang04** [comment]
> word1[i]!=word2[j]时只要考虑两种情况
> 
> * dp[i-1][j]+1
> * dp[i][j-1]+1
> 
> dp[i-1][j-1]+2包含在上述情况中了
> 
> ```c++
> if(word1[i]==word2[j]){
>         dp[i][j]=dp[i-1][j-1];
>  }
>   else{
>          dp[i][j]=min(dp[i-1][j],dp[i][j-1])+1;
>  }
> ```

没理解啥意思
