### ISSUE TITLE
刷题顺序

### ISSUE THREAD

**Issue by bourne-3** [youngyangyang04/leetcode-master#442]
您好，您的项目非常的棒。我想问一下刷题的顺序是从哪里看。是problems文件夹下面开始吗。我看了下，里面都是按照leetcode的顺序排列而已，以组合的题为例子，应该是先放组合77这道题，可是在刷的过程中39就先出现了。有点困惑

**Comment by youngyangyang04** [comment]
> 您好，您的项目非常的棒。我想问一下刷题的顺序是从哪里看。是problems文件夹下面开始吗。我看了下，里面都是按照leetcode的顺序排列而已，以组合的题为例子，应该是先放组合77这道题，可是在刷的过程中39就先出现了。有点困惑

刷题顺序 是 readme上的顺序哈

**Comment by callmePicacho** [comment]
老哥不看 readme 的吗2333
