### ISSUE TITLE
0072.编辑距离的操作一和操作二的解释似乎有问题

### ISSUE THREAD

**Issue by litianming1024** [youngyangyang04/leetcode-master#614]
最近按照大佬的思路刷题进步很快，但是重新刷到编辑距离的时候我的理解有出入，希望大佬指正
> 操作一：word1增加一个元素，使其word1[i - 1]与word2[j - 1]相同，那么就是以下标i-2为结尾的word1 与 j-1为结尾的word2的最近编辑距离 加上一个增加元素的操作。
即 dp[i][j] = dp[i - 1][j] + 1;

这里dp[i - 1][j]表示以下标i - 2结尾的word1已经变换为以j - 1为结尾的word2的最近编辑距离，由于word1的i - 1下标元素与word2的j -1元素不等，所以需要删除word1中i - 1位置的元素，即word1删除一个元素

> 操作二：word2添加一个元素，使其word1[i - 1]与word2[j - 1]相同，那么就是以下标i-1为结尾的word1 与 j-2为结尾的word2的最近编辑距离 加上一个增加元素的操作。
即 dp[i][j] = dp[i][j - 1] + 1;

同理，因为word1中到i - 1位置的全部元素已经变换为了以j - 2为下标的word2，由于word1中i - 1位置的元素和word2中j - 1位置的元素不相等，所以需要对word1增加word2中j - 1位置的元素，即word1增加一个元素或者word2减少一个元素

**Comment by youngyangyang04** [comment]
有道理！感谢纠正，我会修改一下题解
