### ISSUE TITLE
实现strStr()

### ISSUE THREAD

**Issue by jingshaojing** [youngyangyang04/leetcode-master#724]
本人代码环境：vs2019
有一行代码定义了一个next数组是 `int next[needle.size()]`,会提示错误说needle.size()不是一个常量；
所以我百度用了下面这个`constexpr int n = needle.size()`,但是还是会提示，后来看了一下报错，意思是说needle.size()本身就不是constexpr声明的函数，所以不知道这里怎么定义通过编译的。

**Comment by youngyangyang04** [comment]
不用的编译器规则是不一样的，我用的linux下gcc编译， 你把 int next[needle.size()] 中的needle.size() 改为一个 固定值 就可以了

**Comment by jingshaojing** [comment]
好的谢谢大佬，换了常值行。我把原来定义数组的定义成了vector也行。辛苦解答。
