### ISSUE TITLE
动态规划递推公式有问题

### ISSUE THREAD

**Issue by qiufeihong2018** [youngyangyang04/leetcode-master#931]
卡尔哥：
具体问题链接如下：
https://programmercarl.com/0746.%E4%BD%BF%E7%94%A8%E6%9C%80%E5%B0%8F%E8%8A%B1%E8%B4%B9%E7%88%AC%E6%A5%BC%E6%A2%AF.html#%E6%80%9D%E8%B7%AF

![image](https://user-images.githubusercontent.com/36500514/144801423-d596afbc-20a6-400f-89f6-5c16a34518bc.png)

为什么递推公式是这个：dp[i] = min(dp[i - 1], dp[i - 2]) + cost[i]);
不应该是无论前一步还是，还是后一步，只要求到第i步上的花费，都应该要加上cost[i]吧。

递推公式是不是应该是这个：dp[i] = min(dp[i - 1] + cost[i], dp[i - 2]) + cost[i]);

**Comment by Frogrey** [comment]
仔细看一下括号位置

**Comment by qiufeihong2018** [comment]
已解决

**Comment by chengleqi** [comment]
> 已解决

解决的话可以将Issue关闭 :)
